In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/timeseries.csv')

In [2]:
df.head()

Date      A       B       C      D      E      F      G
0  2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87  63.44
1  2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76  59.98
2  2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04  59.61
3  2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84  59.41
4  2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02  60.09

In [3]:
df.shape

(11, 8)

In [4]:
df.index=df.Date
df.head()

Date      A       B       C      D      E      F      G
Date                                                                     
2008-03-18  2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87  63.44
2008-03-19  2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76  59.98
2008-03-20  2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04  59.61
2008-03-25  2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84  59.41
2008-03-26  2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02  60.09

In [5]:
y=df['G']
df=df.drop(['Date','G'],axis=1)


In [6]:
print(df.values)
print(df.shape)

[[ 24.68 164.93 114.73  26.27  19.21  28.87]
 [ 24.18 164.89 114.75  26.22  19.07  27.76]
 [ 23.99 164.63 115.04  25.78  19.01  27.04]
 [ 24.14 163.92 114.85  27.41  19.61  27.84]
 [ 24.44 163.45 114.84  26.86  19.53  28.02]
 [ 24.38 163.46 115.4   27.09  19.72  28.25]
 [ 24.32 163.22 115.56  27.13  19.63  28.24]
 [ 24.19 164.02 115.54  26.74  19.55  28.43]
 [ 23.81 163.59 115.72  27.82  20.21  29.17]
 [ 24.03 163.32 115.11  28.22  20.42  29.38]
 [ 24.34 163.34 115.17  28.14  20.36  29.51]]
(11, 6)


In [7]:
x=[]
y_train=[]
values=df.values
for i in range (len(values)):
    x.append([list(values[i])])
    y_train.append([y[i]])

In [8]:
y_train

[[63.44],
 [59.98],
 [59.61],
 [59.41],
 [60.09],
 [59.62],
 [58.65],
 [59.2],
 [56.18],
 [56.64],
 [57.49]]

In [9]:
x

[[[24.68, 164.93, 114.73, 26.27, 19.21, 28.87]],
 [[24.18, 164.89, 114.75, 26.22, 19.07, 27.76]],
 [[23.99, 164.63, 115.04, 25.78, 19.01, 27.04]],
 [[24.14, 163.92, 114.85, 27.41, 19.61, 27.84]],
 [[24.44, 163.45, 114.84, 26.86, 19.53, 28.02]],
 [[24.38, 163.46, 115.4, 27.09, 19.72, 28.25]],
 [[24.32, 163.22, 115.56, 27.13, 19.63, 28.24]],
 [[24.19, 164.02, 115.54, 26.74, 19.55, 28.43]],
 [[23.81, 163.59, 115.72, 27.82, 20.21, 29.17]],
 [[24.03, 163.32, 115.11, 28.22, 20.42, 29.38]],
 [[24.34, 163.34, 115.17, 28.14, 20.36, 29.51]]]

In [10]:
type(y_train)

list

In [11]:
df['x']=x
df

A       B       C      D      E      F  \
Date                                                     
2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87   
2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76   
2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04   
2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84   
2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02   
2008-03-27  24.38  163.46  115.40  27.09  19.72  28.25   
2008-03-28  24.32  163.22  115.56  27.13  19.63  28.24   
2008-03-31  24.19  164.02  115.54  26.74  19.55  28.43   
2008-04-01  23.81  163.59  115.72  27.82  20.21  29.17   
2008-04-02  24.03  163.32  115.11  28.22  20.42  29.38   
2008-04-03  24.34  163.34  115.17  28.14  20.36  29.51   

                                                         x  
Date                                                        
2008-03-18  [[24.68, 164.93, 114.73, 26.27, 19.21, 28.87]]  
2008-03-19  [[24.18, 164.89, 114.75, 26.22, 19.07, 27.76]]  
2008-03-20  [[23.99, 164.63, 115.04, 25.78, 19.01, 27.04]]  
2008-03-25  [[24.14, 163.92, 114.85, 27.41, 19.61, 27.84]]  
2008-03-26  [[24.44, 163.45, 114.84, 26.86, 19.53, 28.02]]  
2008-03-27   [[24.38, 163.46, 115.4, 27.09, 19.72, 28.25]]  
2008-03-28  [[24.32, 163.22, 115.56, 27.13, 19.63, 28.24]]  
2008-03-31  [[24.19, 164.02, 115.54, 26.74, 19.55, 28.43]]  
2008-04-01  [[23.81, 163.59, 115.72, 27.82, 20.21, 29.17]]  
2008-04-02  [[24.03, 163.32, 115.11, 28.22, 20.42, 29.38]]  
2008-04-03  [[24.34, 163.34, 115.17, 28.14, 20.36, 29.51]]

In [12]:
x_train=df['x'].cumsum()

In [13]:
x[2]

[[23.99, 164.63, 115.04, 25.78, 19.01, 27.04]]

In [14]:
x_train

Date
2008-03-18       [[24.68, 164.93, 114.73, 26.27, 19.21, 28.87]]
2008-03-19    [[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],...
2008-03-20    [[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],...
2008-03-25    [[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],...
2008-03-26    [[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],...
2008-03-27    [[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],...
2008-03-28    [[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],...
2008-03-31    [[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],...
2008-04-01    [[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],...
2008-04-02    [[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],...
2008-04-03    [[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],...
Name: x, dtype: object

In [15]:
type(x_train)

pandas.core.series.Series

In [16]:
x_train[2]

[[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],
 [24.18, 164.89, 114.75, 26.22, 19.07, 27.76],
 [23.99, 164.63, 115.04, 25.78, 19.01, 27.04]]

In [17]:
import keras

Using TensorFlow backend.


In [18]:
from keras.preprocessing.sequence import pad_sequences
x_train_new=pad_sequences(x_train,11)

In [19]:
x_train_new

array([[[  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [ 24, 164, 114,  26,  19,  28]],

       [[  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [ 24, 164, 114,  26,  19,  28],
        [ 24, 164, 114,  26,  19,  27]],

       [[  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   

In [20]:
x_train_new.shape

(11, 11, 6)

In [21]:
y_train=np.array(y_train)
y_train

array([[63.44],
       [59.98],
       [59.61],
       [59.41],
       [60.09],
       [59.62],
       [58.65],
       [59.2 ],
       [56.18],
       [56.64],
       [57.49]])

In [22]:
from keras.models import Sequential
from keras.layers import Dense,LSTM

Input layer

In [23]:
s=x_train_new.shape
print(s)
model=Sequential()
model.add(LSTM(10,input_dim=s[2],input_length=s[1]))

(11, 11, 6)
Instructions for updating:
Colocations handled automatically by placer.


c:\users\naga sri navya\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  after removing the cwd from sys.path.
c:\users\naga sri navya\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(10, input_shape=(11, 6))`
  after removing the cwd from sys.path.


Hidden layer

In [24]:
model.add(Dense(10,activation='relu'))

Output layer

In [25]:
model.add(Dense(1))
model.compile(loss='mean_squared_error',optimizer='sgd',metrics=['mse','mae'])
history=model.fit(x_train_new,y_train,batch_size=11,epochs=300)

Instructions for updating:
Use tf.cast instead.
Epoch 1/300
11/11 [==============================] - 1s 101ms/step - loss: 3489.2515 - acc: 0.0000e+00 - mean_squared_error: 3489.2515 - mean_absolute_error: 59.0409
Epoch 2/300
11/11 [==============================] - 0s 998us/step - loss: 2543.4065 - acc: 0.0000e+00 - mean_squared_error: 2543.4065 - mean_absolute_error: 50.4013
Epoch 3/300
11/11 [==============================] - 0s 855us/step - loss: 958.7842 - acc: 0.0000e+00 - mean_squared_error: 958.7842 - mean_absolute_error: 30.2829
Epoch 4/300
11/11 [==============================] - 0s 544us/step - loss: 3406.1523 - acc: 0.0000e+00 - mean_squared_error: 3406.1523 - mean_absolute_error: 58.3303
Epoch 5/300
11/11 [==============================] - 0s 907us/step - loss: 3181.0063 - acc: 0.0000e+00 - mean_squared_error: 3181.0063 - mean_absolute_error: 56.3693
Epoch 6/300
11/11 [==============================] - 0s 544us/step - loss: 3055.1775 - acc: 0.0000e+00 - mean_squared_error:

In [26]:
model.predict(x_train_new)

array([[58.97654],
       [58.97654],
       [58.97654],
       [58.97654],
       [58.97654],
       [58.97654],
       [58.97654],
       [58.97654],
       [58.97654],
       [58.97654],
       [58.97654]], dtype=float32)